#####################################################
##  ____                                        _  ##
## |  _ \  (_)  ___    ___    ___    _ __    __| | ##
## | | | | | | / __|  / __|  / _ \  | '__|  / _` | ##
## | |_| | | | \__ \ | (__  | (_) | | |    | (_| | ##
## |____/  |_| |___/  \___|  \___/  |_|     \__,_| ##
##   _____              _             _            ##
##  |_   _| (_)   ___  | | __   ___  | |_   ___    ##
##    | |   | |  / __| | |/ /  / _ \ | __| / __|   ##
##    | |   | | | (__  |   <  |  __/ | |_  \__ \   ##
##    |_|   |_|  \___| |_|\_\  \___|  \__| |___/   ##
##                                                 ##
##    Documentation: https://discordtickets.app    ##
##    Support:        https://lnk.earth/discord    ##
#####################################################

logs:
  files:
    directory: ./logs
    enabled: true
    keepFor: 30
  level: info
presence:
  activities:
    - name: "ðŸŽ« play.hydexmc.net"
  interval: 20
  status: online
stats: true
templates:
  transcript: transcript.md
updates: true
